service: websocket-chat


provider:
  name: aws
  runtime: nodejs12.x
  stackName: ${self:service}-${self:provider.stage}
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "execute-api:ManageConnections"
      Resource:
        - "arn:aws:execute-api:*:*:**/@connections/*"
    - Effect: Allow
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:GetItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:BatchGetItem"
        - "dynamodb:BatchWriteItem"
        - "dynamodb:Query"
      Resource:
         - Fn::GetAtt: [ApplicationDynamoDBTable, Arn]
         - Fn::Join:
            - '/'
            - - Fn::GetAtt: [ApplicationDynamoDBTable, Arn]
              - '*'
  environment:
    APPLICATION_TABLE:
      Ref: ApplicationDynamoDBTable
    API_REGION: "${self:provider.region}"

  websocketsApiName: websocket-chat-${self:provider.stage}
  websocketsApiRouteSelectionExpression: $request.body.action

functions:
  connect:
    handler: src/handlers.connect
    events:
      - websocket:
          route: $connect

  disconnect:
    handler: src/handlers.disconnect
    events:
      - websocket:
          route: $disconnect

  sendMessage:
    handler: src/handlers.sendMessage
    events:
       - websocket:
           route: sendMessage

  subscribeChannel:
    handler: src/handlers.subscribeChannel
    events:
       - websocket:
           route: subscribeChannel 

  unsubscribeChannel:
    handler: src/handlers.unsubscribeChannel
    events:
      - websocket:
          route: unsubscribeChannel

resources: 
  Resources:
    ApplicationDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: reverse
            KeySchema:
              - AttributeName: sk
                KeyType: HASH
              - AttributeName: pk
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
                
    
    
